# SPDX-FileCopyrightText: 2017-2021, Carles Fernandez-Prades <carles.fernandez@cttc.es>
# SPDX-License-Identifier: MIT

name: Simple CI

on: [push, pull_request]

jobs:
  REUSE-compliance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check REUSE compliance
      uses: docker://fsfe/reuse
      with:
        args: lint
